[build]
  publish = "build/"
  command = "yarn test && yarn build"

[[redirects]]
  from = "https://roland-codes.netlify.com/*"
  to = "https://roland.codes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://roland.codes/*"
  to = "https://roland.codes/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    Expect-Ct = "max-age=0"
    Content-Security-Policy = "base-uri 'none'; block-all-mixed-content; connect-src 'self' https://api.github.com https://www.google-analytics.com; default-src 'self'; form-action 'self'; frame-ancestors 'self'; frame-src 'self' https://codepen.io; img-src *; object-src 'none'; script-src 'self' https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; style-src-elem 'self'; upgrade-insecure-requests"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=31536000"
    X-Dns-Prefetch-Control = "off"
    X-Download-Options = "noopen"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
